version: '3.8'

services:
  playwright-screenshotter:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./results:/app/results
    environment:
      - NODE_ENV=production
      - EXTERNAL_IP=${EXTERNAL_IP:-127.0.0.1}
    command: node server-only.js 3000
    restart: unless-stopped

networks:
  default:
    name: playwright-network
